services:

  # ======================
  # BASE DE DATOS CITAS
  # ======================
  db_citas:
    image: postgres:15
    container_name: db_citas
    environment:
      POSTGRES_DB: citas_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./database/citas/init.sql:/docker-entrypoint-initdb.d/init.sql

  # ======================
  # BASE DE DATOS INVENTARIO
  # ======================
  db_inventario:
    image: postgres:15
    container_name: db_inventario
    environment:
      POSTGRES_DB: inventario_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - ./database/inventario/init.sql:/docker-entrypoint-initdb.d/init.sql

  # ======================
<<<<<<< HEAD
  # BASE DE DATOS USUARIOS
  # ======================
  db_usuarios:
    image: postgres:15
    container_name: db_usuarios
    environment:
      POSTGRES_DB: usuarios_db
=======
  # BASE DE DATOS HISTORIAL
  # ======================
  db_historial:
    image: postgres:15
    container_name: db_historial
    environment:
      POSTGRES_DB: historial_db
>>>>>>> 693fb39 (Microservicios con historial de vehiculos y clientes con 8 endpoints)
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
<<<<<<< HEAD
=======
    volumes:
      - ./database/historial/init.sql:/docker-entrypoint-initdb.d/init.sql
>>>>>>> 693fb39 (Microservicios con historial de vehiculos y clientes con 8 endpoints)

  # ======================
  # MICROSERVICIO CITAS
  # ======================
  citas_service:
    build: ./backend/microservicio_citas
    ports:
      - "8000:8000"
    depends_on:
      - db_citas

  # ======================
  # MICROSERVICIO INVENTARIO
  # ======================
  inventario_service:
    build: ./backend/microservicio_inventario
    ports:
      - "8001:8001"
    depends_on:
      - db_inventario

  # ======================
<<<<<<< HEAD
  # MICROSERVICIO USUARIOS
  # ======================
  usuarios_service:
    build: ./backend/microservicio_usuarios
    ports:
      - "8002:8002"
    depends_on:
      - db_usuarios
=======
  # MICROSERVICIO HISTORIAL
  # ======================
  historial_service:
    build: ./backend/microservicio_historial
    ports:
      - "8002:8002"
    depends_on:
      - db_historial
>>>>>>> 693fb39 (Microservicios con historial de vehiculos y clientes con 8 endpoints)
