name: Backend Inventario CI

on:
  push:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - run: pip install -r backend/microservicio_inventario/requirements.txt

      - run: pytest
        working-directory: backend/microservicio_inventario